import type { BoxData } from "./types.js";

/** Hardcoded test boxes for offline mode (16 balls in 4×4 grid, 1-3 correct) */
export const TEST_BOXES: BoxData[] = [
  {
    categoryName: "Golden Retriever",
    hideLabels: true,
    roundNumber: 1,
    timeLimitMs: 15000,
    helperMode: true,
    balls: [
      { id: 1, label: "Golden Retriever", isCorrect: true },
      { id: 2, label: "Labrador", isCorrect: false },
      { id: 3, label: "Poodle", isCorrect: false },
      { id: 4, label: "German Shepherd", isCorrect: false },
      { id: 5, label: "Bulldog", isCorrect: false },
      { id: 6, label: "Beagle", isCorrect: false },
      { id: 7, label: "Husky", isCorrect: false },
      { id: 8, label: "Dalmatian", isCorrect: false },
      { id: 9, label: "Corgi", isCorrect: false },
      { id: 10, label: "Shiba Inu", isCorrect: false },
      { id: 11, label: "Rottweiler", isCorrect: false },
      { id: 12, label: "Doberman", isCorrect: false },
      { id: 13, label: "Chihuahua", isCorrect: false },
      { id: 14, label: "Pomeranian", isCorrect: false },
      { id: 15, label: "Great Dane", isCorrect: false },
      { id: 16, label: "Boxer", isCorrect: false },
    ],
  },
  {
    categoryName: "Harry Potter Characters",
    roundNumber: 2,
    timeLimitMs: 15000,
    helperMode: true,
    balls: [
      { id: 101, label: "Harry Potter", isCorrect: true },
      { id: 102, label: "Hermione", isCorrect: true },
      { id: 103, label: "Ron Weasley", isCorrect: true },
      { id: 104, label: "Gandalf", isCorrect: false },
      { id: 105, label: "Yoda", isCorrect: false },
      { id: 106, label: "Merlin", isCorrect: false },
      { id: 107, label: "Doctor Strange", isCorrect: false },
      { id: 108, label: "Saruman", isCorrect: false },
      { id: 109, label: "Elphaba", isCorrect: false },
      { id: 110, label: "Maleficent", isCorrect: false },
      { id: 111, label: "Link", isCorrect: false },
      { id: 112, label: "Princess Zelda", isCorrect: false },
      { id: 113, label: "Radagast", isCorrect: false },
      { id: 114, label: "Dumbledore", isCorrect: true },
      { id: 115, label: "Voldemort", isCorrect: true },
      { id: 116, label: "Pikachu", isCorrect: false },
    ],
  },
];
